### ISSUE TITLE
train_speller()

### ISSUE THREAD

**Issue by harishdamera** [MajorTal/DeepSpell#14]
If I run train_speller(), I get the below error.

generator_output = next(output_generator)

StopIteration

Do I have to run    train_speller(os.path.join(DATA_FILES_FULL_PATH, "keras_spell_e15.h5")) 
before train_speller().

I get the below error if I run train_speller(os.path.join(DATA_FILES_FULL_PATH, "keras_spell_e15.h5")) 

OSError: Unable to open file (Unable to open file: name = '/users/harish/desktop/testing/deepspell/downloads/data/keras_spell_e15.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by MajorTal** [comment]
Please run all the steps that are commented out in the __main__ one by one.

Thanks,

Tal Weiss
+31-6-1165-8778
Skype: major.tal
https://twitter.com/majortal
