### ISSUE TITLE
tensorflow or theano?

### ISSUE THREAD

**Issue by vinnitu** [MajorTal/DeepSpell#5]
How to make choice to get best results? Why?

**Comment by MajorTal** [comment]
Try both?
I have nothing better here. I don't really care what the underlying tensor library is.
My specific experience for this specific network on my servers for a specific set of library revisions:
Theano takes a longer time to "compile" - to start the script,  which is annoying.
But TensorFlow is slower to train.

**Comment by vinnitu** [comment]
thx
